name: JARVIS CI — Lint & Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install lightweight test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov flake8
          pip install langchain-core langchain-community
          pip install sentence-transformers
          pip install faiss-cpu
          pip install tiktoken python-dotenv PyPDF2

      - name: Lint (syntax errors & undefined names only)
        run: flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Test
        run: pytest tests/ -v --tb=short
        env:
          OPENAI_API_KEY: "sk-test-placeholder"
          GOOGLE_API_KEY: "test-placeholder"